name: olx_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Back-end
  parse_server_sdk_flutter: ^3.1.0

  # Image selector
  image_picker: ^0.8.4+8

  # MobX
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  
  # Service Locator
  get_it: ^7.2.0

  # Formatter for Brazilian pattern
  brasil_fields: ^1.3.1

  # Image edition
  image_cropper: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Good practices
  flutter_lints: ^1.0.0

  # Code generator
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2

flutter:

  uses-material-design: true